from . import account
from . import change_password
from . import chatbot
from . import home
from . import loading
from . import place_details
from . import privacy_politics
from . import sign_in
from . import sign_up
from . import terms_conditions
